"""Add notification settings table

Revision ID: 3221018daf1a
Revises: e52680919a32
Create Date: 2026-08-04 08:33:19.462961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3221018daf1a'
down_revision = 'e52680919a32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_email', sa.String(length=120), nullable=False),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('notify_negative', sa.Boolean(), nullable=False),
    sa.Column('notify_neutral', sa.Boolean(), nullable=False),
    sa.Column('notify_positive', sa.Boolean(), nullable=False),
    sa.Column('minimum_confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification_settings')
    # ### end Alembic commands ###
