"""Add daily summary settings

Revision ID: 52c6b98cfbfb
Revises: 3221018daf1a
Create Date: 2026-08-04 09:34:56.786756

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "52c6b98cfbfb"
down_revision = "3221018daf1a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted ###

    with op.batch_alter_table(
        "notification_settings",
        schema=None,
    ) as batch_op:

        batch_op.add_column(
            sa.Column(
                "daily_summary_enabled",
                sa.Boolean(),
                nullable=False,
                server_default=sa.true(),
            )
        )

        batch_op.add_column(
            sa.Column(
                "daily_summary_time",
                sa.String(length=5),
                nullable=False,
                server_default="20:00",
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###

    with op.batch_alter_table(
        "notification_settings",
        schema=None,
    ) as batch_op:

        batch_op.drop_column("daily_summary_time")
        batch_op.drop_column("daily_summary_enabled")

    # ### end Alembic commands ###